# travis-ci.org configuration
# 
language: perl
perl:
    - "5.20"
addons:
    apt:
        packages:
        - libdb-dev
        - libdb5.1
install:
    - cpanm install --quiet --notest BerkeleyDB
    - cpanm install --quiet --notest Net::Server::Multiplex
    - cpanm install --quiet --notest NetAddr::IP
    - cpanm install --quiet --notest File::Slurper
script:
    - test/test.pl
